language: node_js
node_js:
  - "stable"
script:
  - npm run build #Creats a production build
  - npm run test #Runs Tests
addons:
    code_climate:
        repo_token: "c2f07c4d7637d6861c9e90710f084e709440dd7a9f3a886b7dc05521e9a7bb3a" 
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_success:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info